### ISSUE TITLE
ES6 compatibility

### ISSUE THREAD

**Issue by stagemteam** [alexindigo/configly#56]
I use ES6 in my project and want to export config like this
```js
// src/photo/config/route.js
export default [
  {
    path: "/users",
    method: "get",
    //action: AllAction
  },
  // ...
];
```

Here my `configly` configuration
```js
let oneConfig = configly({
  files: configly.files.concat('D:\\path\\to\\project\src\\photo\\config\\route')
});
```
but during compilation I get error
```
D:\WebServer\git\selection\selection\node_modules\configly\lib\load_files.js:100
    throw new Error('Config file ' + file + ' cannot be read or malformed: ' + e.message);
          ^
Error: Config file D:\WebServer\git\selection\selection\src\photo\config\route.js cannot be read or malformed: Unexpected token export
    at Function.loadContent (D:\WebServer\git\selection\selection\node_modules\configly\lib\load_files.js:100:11)
    at D:\WebServer\git\selection\selection\node_modules\configly\lib\load_files.js:44:29
    at Array.forEach (<anonymous>)
    at D:\WebServer\git\selection\selection\node_modules\configly\lib\load_files.js:38:19
    at Array.forEach (<anonymous>)
    at D:\WebServer\git\selection\selection\node_modules\configly\lib\load_files.js:34:16
    at Array.forEach (<anonymous>)
    at Function.loadFiles (D:\WebServer\git\selection\selection\node_modules\configly\lib\load_files.js:30:9)
    at Function.load (D:\WebServer\git\selection\selection\node_modules\configly\lib\load.js:44:22)
    at Function.configly (D:\WebServer\git\selection\selection\node_modules\configly\lib\configly.js:29:10)
```

Is there any possibility to work with `configly` in ES6?

**Comment by alexindigo** [comment]
Thanks for you interest in the package.

`configly` itself has no opinion on JS flavor, it executes within nodejs and nodejs is pasing and executing all the files. Latest version of nodejs support ES6.

And in your example it's ES modules syntax, that Nodejs doesn't support yet, and which usually gets compiled to commonjs (`const bla = require(...)`).
Looks like you're trying to load uncompiled files.

Curious how do you run your project? Webpack or something else?

PS. Also configly usually used at runtime, means it would execute with already built/compiled code,
so you might try to point it to your `dist` folder, like:

```
let oneConfig = configly({
  files: configly.files.concat('D:\\path\\to\\project\\dist\\photo\\config\\route')
});
```

**Comment by alexindigo** [comment]
It's been quite a while. I'll close it for now. Feel free to ping me if you have more questions.
